//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamPomodoro.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamPomodoro.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a project first. If there is no project to choose, please add a project before creating the task..
        /// </summary>
        public static string MsgAddProjects {
            get {
                return ResourceManager.GetString("MsgAddProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be found. Would you like to create account?.
        /// </summary>
        public static string MsgUserCannotBeFound {
            get {
                return ResourceManager.GetString("MsgUserCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified name already exists..
        /// </summary>
        public static string MsgUserExists {
            get {
                return ResourceManager.GetString("MsgUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TxtAdd {
            get {
                return ResourceManager.GetString("TxtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string TxtAddProject {
            get {
                return ResourceManager.GetString("TxtAddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TxtAddTask {
            get {
                return ResourceManager.GetString("TxtAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add team.
        /// </summary>
        public static string TxtAddTeam {
            get {
                return ResourceManager.GetString("TxtAddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string TxtAdmin {
            get {
                return ResourceManager.GetString("TxtAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TxtCancel {
            get {
                return ResourceManager.GetString("TxtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string TxtChoose {
            get {
                return ResourceManager.GetString("TxtChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TxtDate {
            get {
                return ResourceManager.GetString("TxtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TxtDelete {
            get {
                return ResourceManager.GetString("TxtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        public static string TxtDetails {
            get {
                return ResourceManager.GetString("TxtDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string TxtDuration {
            get {
                return ResourceManager.GetString("TxtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TxtEdit {
            get {
                return ResourceManager.GetString("TxtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string TxtEditProject {
            get {
                return ResourceManager.GetString("TxtEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Projects....
        /// </summary>
        public static string TxtEditProjects {
            get {
                return ResourceManager.GetString("TxtEditProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string TxtEditTask {
            get {
                return ResourceManager.GetString("TxtEditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tasks....
        /// </summary>
        public static string TxtEditTasks {
            get {
                return ResourceManager.GetString("TxtEditTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Team.
        /// </summary>
        public static string TxtEditTeam {
            get {
                return ResourceManager.GetString("TxtEditTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Teams....
        /// </summary>
        public static string TxtEditTeams {
            get {
                return ResourceManager.GetString("TxtEditTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong....
        /// </summary>
        public static string TxtError {
            get {
                return ResourceManager.GetString("TxtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TxtExit {
            get {
                return ResourceManager.GetString("TxtExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string TxtFailed {
            get {
                return ResourceManager.GetString("TxtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note....
        /// </summary>
        public static string TxtInfo {
            get {
                return ResourceManager.GetString("TxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string TxtMinutes {
            get {
                return ResourceManager.GetString("TxtMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string TxtNewTask {
            get {
                return ResourceManager.GetString("TxtNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TxtNo {
            get {
                return ResourceManager.GetString("TxtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pomodoros required for the task:.
        /// </summary>
        public static string TxtNumberOfPomodoros {
            get {
                return ResourceManager.GetString("TxtNumberOfPomodoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TxtOk {
            get {
                return ResourceManager.GetString("TxtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro details.
        /// </summary>
        public static string TxtPomodoroDetails {
            get {
                return ResourceManager.GetString("TxtPomodoroDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro duration.
        /// </summary>
        public static string TxtPomodoroDuration {
            get {
                return ResourceManager.GetString("TxtPomodoroDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoros.
        /// </summary>
        public static string TxtPomodoroes {
            get {
                return ResourceManager.GetString("TxtPomodoroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro {0} of {1}.
        /// </summary>
        public static string TxtPomodoroXofY {
            get {
                return ResourceManager.GetString("TxtPomodoroXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TxtProject {
            get {
                return ResourceManager.GetString("TxtProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string TxtProjectName {
            get {
                return ResourceManager.GetString("TxtProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TxtProjects {
            get {
                return ResourceManager.GetString("TxtProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TxtSave {
            get {
                return ResourceManager.GetString("TxtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warning after pomodoro expires.
        /// </summary>
        public static string TxtShowWarning {
            get {
                return ResourceManager.GetString("TxtShowWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string TxtSignIn {
            get {
                return ResourceManager.GetString("TxtSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string TxtSignOut {
            get {
                return ResourceManager.GetString("TxtSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TxtStart {
            get {
                return ResourceManager.GetString("TxtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TxtStartTime {
            get {
                return ResourceManager.GetString("TxtStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TxtStop {
            get {
                return ResourceManager.GetString("TxtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TxtStopTime {
            get {
                return ResourceManager.GetString("TxtStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string TxtSuccessful {
            get {
                return ResourceManager.GetString("TxtSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TxtTask {
            get {
                return ResourceManager.GetString("TxtTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        public static string TxtTaskName {
            get {
                return ResourceManager.GetString("TxtTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TxtTasks {
            get {
                return ResourceManager.GetString("TxtTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TxtTeam {
            get {
                return ResourceManager.GetString("TxtTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string TxtTeamName {
            get {
                return ResourceManager.GetString("TxtTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Pomodoro.
        /// </summary>
        public static string TxtTeamPomodoro {
            get {
                return ResourceManager.GetString("TxtTeamPomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string TxtTeams {
            get {
                return ResourceManager.GetString("TxtTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TxtTotal {
            get {
                return ResourceManager.GetString("TxtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string TxtUser {
            get {
                return ResourceManager.GetString("TxtUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string TxtUserName {
            get {
                return ResourceManager.GetString("TxtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string TxtUserSettings {
            get {
                return ResourceManager.GetString("TxtUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works in team.
        /// </summary>
        public static string TxtWorksInTeam {
            get {
                return ResourceManager.GetString("TxtWorksInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TxtYes {
            get {
                return ResourceManager.GetString("TxtYes", resourceCulture);
            }
        }
    }
}
