//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamPomodoro.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamPomodoro.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server failed to repond..
        /// </summary>
        public static string MsgFailedToRespond {
            get {
                return ResourceManager.GetString("MsgFailedToRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be found. Would you like to create account?.
        /// </summary>
        public static string MsgUserCannotBeFound {
            get {
                return ResourceManager.GetString("MsgUserCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified name already exists..
        /// </summary>
        public static string MsgUserExists {
            get {
                return ResourceManager.GetString("MsgUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TxtAdd {
            get {
                return ResourceManager.GetString("TxtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TxtEdit {
            get {
                return ResourceManager.GetString("TxtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string TxtMinutes {
            get {
                return ResourceManager.GetString("TxtMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro duration:.
        /// </summary>
        public static string TxtPomodoroDuration {
            get {
                return ResourceManager.GetString("TxtPomodoroDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoros.
        /// </summary>
        public static string TxtPomodoroes {
            get {
                return ResourceManager.GetString("TxtPomodoroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodoro {0} of {1}.
        /// </summary>
        public static string TxtPomodoroXofY {
            get {
                return ResourceManager.GetString("TxtPomodoroXofY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warning after pomodoro expires.
        /// </summary>
        public static string TxtShowWarning {
            get {
                return ResourceManager.GetString("TxtShowWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string TxtSignIn {
            get {
                return ResourceManager.GetString("TxtSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TxtStart {
            get {
                return ResourceManager.GetString("TxtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TxtStop {
            get {
                return ResourceManager.GetString("TxtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task:.
        /// </summary>
        public static string TxtTask {
            get {
                return ResourceManager.GetString("TxtTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Pomodoro.
        /// </summary>
        public static string TxtTeamPomodoro {
            get {
                return ResourceManager.GetString("TxtTeamPomodoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string TxtUserName {
            get {
                return ResourceManager.GetString("TxtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string TxtUserSettings {
            get {
                return ResourceManager.GetString("TxtUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works in team:.
        /// </summary>
        public static string TxtWorksInTeam {
            get {
                return ResourceManager.GetString("TxtWorksInTeam", resourceCulture);
            }
        }
    }
}
